version: '2'
services:
    centerman-app:
        image: centerman
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://centerman-mariadb:3306/centerman
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8088:8088
    centerman-mariadb:
        extends:
            file: mariadb.yml
            service: centerman-mariadb
